# Automatically generated by configure - do not modify
TARGET_DIR=i386-dbaf-softmmu
DBAF_SRC_PATH=/home/wb/workspace/qemu-dbaf
DBAF_BUILD_PATH=/home/wb/workspace/build/qemu-dbaf
BUNDLE_NAME=simplebundle
